
# mysql逆向生成
generator:
  # 是否文件覆盖
  overwrite: false

  packageName: com.ymyang
  # dto,param所属modules绝对路径
  modelPath: D:/sources/sso-parent/sso-common/
  # service所属modules绝对路径
  servicePath: D:/sources/sso-parent/sso-service/
  # 控制器所属modules绝对路径
  controllerPath: D:/sources/sso-parent/sso-api/
  # vuejs模板路径
  # vuePath:

  # 表前缀
  tablePrefix: t_

  modules:
    # 模块名
    - name: sso
    # 需要生成的表名列表
      tables:
        #- t_action_define
        #- t_action_log
      views:
        #- {name: v_activity_info, comment: 活动}
        #- {name: v_activity_prize, comment: 活动奖品}
